config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	
	extend Enumerize
	enumerize :level, in: [:easy, :medium, :hard], default: :easy
	enumerize :country, in: ISO3166::Country.translations, default: :Germany
	enumerize :title, in: [:ruby, :medium, :hard], default: :ruby

	validates :title, :description, presence: true
	validate :title_is_shorter_than_description
	scope :price, -> (price) {where('price < ?', price)}
	before_save :strip_html_from_description
	def strip_html_from_description
		self.description = ActionView::Base.full_sanitizer.sanitize(self.description)
	end
	def title_is_shorter_than_description
		return if title.blank? || description.blank?
		if description.length < title.length
			errors.add(:description, 'can\'t be shorter than title')
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end
	def show
		@product = Product.find(params[:id])
	end
	def new
		@product = Product.new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% @products.each do |product| %>
<div>
	<h1><%= product.title %></h1>
	<a><%= product.price %></a>
</div>
<%= link_to('Read more', product) %>
<% end %>

<%= link_to('create', new_product_url) %>

app/views/products/new.erb
<%= semantic_form_for @product do |f| %>
	<%= f.input :title %>
	<%= f.input :description %>
	<%= f.input :price %>
	<%= f.input :published, min: 0.01 %>
	<%= f.input :country %>
	<%= f.input :level %>
	<%= f.action :submit %>
<%end%>

app/views/products/show.erb
<div>
	<h1>Detail</h1>
	<ul>
		<li><%= @product.title %></li>
		<li><%= @product.description %></li>
		<li><%= @product.price %></li>
	</ul>
</div>